### ISSUE TITLE
Remove RXU in favor of rxu in netlabs-rel

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/rpm-issues#2]
Currently, both of the following packages exist in netlabs-rel:

RXU-1.a.0-1.oc00.i686.rpm
rxu-1.a.0-3.oc00.i686.rpm

Unfortunately, our need for case insensitivity works to our disadvantage, here, as creatrepo sees two distinct packages and lists them separately, even though rxu-1.a.0-3 should be an update to RXU-1.a.0-1. This causes some confusion for users.

This is but one example. We've run into issues with SDL vs sdl, as well.

Suggest removing the conflicted older packages, as the Obsoletes tag is not sufficient to avoid the confusion in package listings (after updating from RXU to rxu, RXU continues to be listed as available by yum).

**Comment by SilvanScherrer** [comment]
Rpm per se is not case insensitive. So having CamelCase rpm is valid and will always be the case. Rpm handles the obsolete tag very well, so it's not a real issue. The package listing is another case of course.
And as in this case it's wrong to have both we will remove one soon.
Don't mention SDL, as I told the author since ages to fix his mess.

**Comment by SilvanScherrer** [comment]
hm I did some tests with RXU and the obsoletes works like a charm. So closing this issue as not an issue.
